services:
  mongo:
    image: mongo
    container_name: abacws-chatbot-mongo
    hostname: mongohost
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - my_bridge

  api:
    image: ghcr.io/suhasdevmane/abacws-chatbot:api-main
    container_name: abacws-api
    hostname: apihost
    restart: always
    depends_on:
      - mongo
    environment:
      - API_PORT=5000
    ports:
      - 8091:5000
    volumes:
      - api-data:/api/api/data
    networks:
      - my_bridge

  visualiser:
    image: ghcr.io/suhasdevmane/abacws-chatbot:visualiser-main
    container_name: abacws-visualiser
    hostname: visualiserhost
    restart: always
    depends_on:
      - api
    ports:
      - 8090:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.abacws-visualiser.loadbalancer.server.port=80"
      - "traefik.http.routers.abacws-visualiser.rule=Host(`visualiser.abacws.example.com`)"
      - "traefik.http.routers.abacws-visualiser.entrypoints=https"
      - "traefik.http.routers.abacws-visualiser.tls=true"
    networks:
      - my_bridge

networks:
  my_bridge:
volumes:
  mongo-data:
  api-data:
