version: "3"

services:
  thingsboard:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
    volumes:
      - thingsboard-data:/data
      - thingsboard-logs:/var/log/thingsboard
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - tb-net

  timescaledb:
    image: "timescale/timescaledb:latest-pg14"
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=timescale
      - POSTGRES_USER=timescale
      - POSTGRES_DB=timescaledb
    ports:
      - "5432:5432" # PostgreSQL Port
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    networks:
      - tb-net

  postgres:
    image: "postgres:14"
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=thingsboard
    ports:
      - "5433:5432" # PostgreSQL Port (use a different host port to avoid conflicts)
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tb-net

networks:
  tb-net:
volumes:
  timescaledb-data:
  postgres-data:
  thingsboard-data:
    external: true
  thingsboard-logs:
    external: true
