version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:/timescaledb-2.12.0-pg14
    container_name: timescaledb
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: thingsboard
      POSTGRES_PASSWORD: thingsboardpassword
    ports:
      - "5432:5432" # Map the PostgreSQL port to the host machine
    networks:
      - thingsboard-network
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  thingsboard:
    image: thingsboard/tb-postgres
    container_name: thingsboard
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://timescaledb:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: thingsboard
      SPRING_DATASOURCE_PASSWORD: thingsboardpassword
    ports:
      - "9090:9090" # Map ThingsBoard port to the host machine
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    volumes:
      - thingsboard-data:/data
      - thingsboard-logs:/var/log/thingsboard
    networks:
      - thingsboard-network
    depends_on:
      - timescaledb

networks:
  thingsboard-network:

volumes:
  timescaledb_data:
  thingsboard-data:
    external: true
  thingsboard-logs:
    external: true
