version: "3"

services:
  fuseki-db:
    image: busybox
    container_name: jena-fuseki-db
    volumes:
      - jena-data:/fuseki
    command: tail -f /dev/null # Keep the container running in the background
    networks:
      - my_bridge

  jena-fuseki:
    image: stain/jena-fuseki
    container_name: jena-fuseki-rdf-store
    ports:
      - "3030:3030"
    volumes_from:
      - fuseki-db
    volumes:
      - ./trial/dataset:/fuseki-data
    restart: always
    environment:
      - ADMIN_PASSWORD=Suhas@551993
    user: "root" # Specify the user as root
    networks:
      - my_bridge

networks:
  my_bridge:

volumes:
  jena-data:
  fuseki:
