version: "3.0"
services:
  thingsboard2:
    # restart: always
    # image: "thingsboard-jupyter:1.0"
    # image: 7499968836/my-thingsboard:1.0
    image: mytb-timescale:1.0.0
    container_name: thingsboard2
    hostname: thingsboardhost
    ports:
      - "8088:9090"
      # - "1883:1883"
      - "7075:7070"
      # - "5683-5688:5683-5688/udp"
      - "8089:8081"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.thingsboard-data:/data
      - ~/.thingsboard-logs:/var/log/thingsboards
    networks:
      - my_bridge

  # timescaledb:
  #   image: "timescale/timescaledb:latest-pg12"
  #   container_name: timescaledb
  #   hostname: timescaledb
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=thingsboard
  #   ports:
  #     - "5432:5432" # PostgreSQL Port (use a different host port to avoid conflicts)
  #   volumes:
  #     - timescaledb-data:/var/lib/postgresql/data
  #   depends_on:
  #     - thingsboard
  #   command: ["-c", "shared_preload_libraries=timescaledb"]
  #   networks:
  #     - my_bridge
# =======================
networks:
  my_bridge:
volumes:
  thingsboard-data:
    external: true
  thingsboard-logs:
    external: true
  # timescaledb-data:
