version: "3.0"
services:
  jena-fuseki:
    image: stain/jena-fuseki
    container_name: jena-fuseki-rdf-store
    hostname: jenahost
    ports:
      - "3030:3030"
    volumes:
      - jena-data:/data
    environment:
      - ADMIN_PASSWORD=Suhas@551993
    restart: always
    networks:
      - my_bridge
networks:
  my_bridge:
volumes:
  jena-data:
