version: "3.0"
services:
  # thingsboard:
  #   image: "thingsboard/tb-postgres:latest"
  #   container_name: thingsboard-abacws
  #   restart: always
  #   ports:
  #     - "8080:9090"
  #     - "1883:1883"
  #     - "7070:7070"
  #     - "5683-5688:5683-5688/udp"
  #   environment:
  #     TB_QUEUE_TYPE: in-memory
  #   volumes:
  #     - thingsboard-data:/data
  #     - thingsboard-logs:/var/log/thingsboard
  #   networks:
  #     - abacws-chatbot_my_bridge

  # timescale:
  #   image: "timescale-12:1.0"
  #   container_name: timescale
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=thingsboard
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - timescaledb-data:/var/lib/postgresql12/data
  #   # command: ["-c", "shared_preload_libraries=timescaledb"]
  #   networks:
  #     - abacws-chatbot_my_bridge

networks:
  abacws-chatbot_my_bridge:
# volumes:
#   thingsboard-data:
#     external: true
#   thingsboard-logs:
#     external: true
# timescaledb-data:

