name: Push Visualiser Docker on Comment

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Comment
        id: check_comment
        run: echo ::set-output name=contains_build_visualiser::$(echo "${{ github.event.comment.body }}" | grep -c 'build-visualiser')

      - name: Checkout repository with lfs
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.actor }}/Abacws-chatbot
          flavor: |
            prefix=visualiser-,onlatest=true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "./visualiser"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        if: steps.check_comment.outputs.contains_build_visualiser == '1'
